name: test variable

on:
  push:

jobs:
  check_php7_sintax:
    name: Check Sintaxe PHP v-7.1
    runs-on: ubuntu-latest
    container:
      image: php:7.1-apache
    steps:
      - run: echo ${{ secrets.DOCKER_ACCOUNT }} >> world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt
